services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"   # <-- map container port 8080 to host port 8080
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"   # optional if you want host access
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
